# Generated by Django 4.0.3 on 2022-04-20 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('victim_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('victim_name', models.CharField(max_length=100)),
                ('victim_gender', models.CharField(max_length=10)),
                ('victim_age', models.IntegerField()),
                ('victim_aadhar', models.CharField(max_length=12)),
                ('victim_email', models.CharField(max_length=100)),
                ('victim_phone', models.CharField(max_length=10)),
                ('victim_password', models.CharField(max_length=20)),
                ('victim_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('officer_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('officer_name', models.CharField(max_length=100)),
                ('officer_email', models.CharField(max_length=100)),
                ('officer_gender', models.CharField(max_length=10)),
                ('officer_designation', models.CharField(max_length=50)),
                ('officer_phone', models.CharField(max_length=10)),
                ('officer_password', models.CharField(max_length=20)),
                ('officer_address', models.CharField(max_length=100)),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.station')),
            ],
        ),
    ]
