# Generated by Django 4.0.3 on 2022-04-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='victim_age',
            field=models.IntegerField(default=0),
        ),
    ]
