# Generated by Django 4.0.3 on 2022-04-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=100)),
                ('station_address', models.CharField(max_length=100)),
                ('station_status', models.CharField(max_length=20)),
            ],
        ),
    ]
