# Generated by Django 4.0.3 on 2022-04-20 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FIR',
            fields=[
                ('fir_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fir_category', models.CharField(max_length=36)),
                ('fir_details', models.CharField(max_length=500)),
                ('fir_datetime', models.DateTimeField(auto_now_add=True)),
                ('fir_suspect', models.CharField(max_length=100)),
                ('fir_status', models.CharField(default='NEW', max_length=20)),
                ('fir_address', models.CharField(max_length=50)),
                ('fir_priority', models.CharField(default='MEDIUM', max_length=20)),
                ('fir_bureau_notes', models.CharField(default='NONE', max_length=500)),
                ('officer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.officer')),
                ('victim_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.victim')),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('log_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('log_action', models.CharField(max_length=500)),
                ('log_datetime', models.DateTimeField(auto_now_add=True)),
                ('fir_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir.fir')),
            ],
        ),
    ]
